Repository 2024-Saphy/BE, pull requests merged in 2024-10, with the labels that each got.

#86 SAPHY-171 feat: redis docker-compose 추가
  docker-compose.yml
  src/main/java/saphy/saphy/auth/presentation/ReissueController.java
  src/main/java/saphy/saphy/auth/service/ReissueService.java
  src/main/java/saphy/saphy/global/config/RedisConfig.java
  src/main/java/saphy/saphy/member/dto/response/MemberDetailResponse.java
Labels: 🐞 Bug, ⚙ Chore, ✨ Feature

#88 SAPHY-70 feat: 기기 등록 기능 (관리자)
  docker-compose.yml
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
Labels: ♻️ Refactor

#89 SAPHY-140 refactor: 결제 기능 리펙토링
  src/main/java/saphy/saphy/pay/domain/Pay.java
  src/main/java/saphy/saphy/pay/domain/repository/PayRepository.java
  src/main/java/saphy/saphy/pay/dto/request/PayCompleteRequest.java
  src/main/java/saphy/saphy/pay/dto/request/PayPrepareRequest.java
  src/main/java/saphy/saphy/pay/dto/request/PayRequest.java
  src/main/java/saphy/saphy/pay/dto/response/PayCompleteResponse.java
  src/main/java/saphy/saphy/pay/dto/response/PayPrepareResponse.java
  src/main/java/saphy/saphy/pay/dto/response/PayResponse.java
  src/main/java/saphy/saphy/pay/presentation/PayController.java
  src/main/java/saphy/saphy/pay/service/PayService.java
  src/main/java/saphy/saphy/sales/domain/Sales.java
Labels: ✨ Feature, ♻️ Refactor

#87 SAPHY-123 feat: 기기 검색 기능 구현
  .gitignore
  build.gradle
  src/main/java/saphy/saphy/global/config/P6SpyConfig.java
  src/main/java/saphy/saphy/global/config/QueryDslConfig.java
  src/main/java/saphy/saphy/global/response/ApiResponse.java
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/item/domain/repository/ItemRepository.java
  src/main/java/saphy/saphy/item/domain/repository/custom/ItemQueryDslRepository.java
  src/main/java/saphy/saphy/item/domain/repository/custom/ItemQueryDslRepositoryImpl.java
  src/main/java/saphy/saphy/item/dto/request/SearchParam.java
  src/main/java/saphy/saphy/item/dto/response/ItemResponse.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#90 SAPHY-55 feat: 상품 구매 현황 조회 기능 구현
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/purchase/domain/PurchaseStatus.java
  src/main/java/saphy/saphy/purchase/domain/repository/PurchaseRepository.java
  src/main/java/saphy/saphy/purchase/dto/response/PurchaseResponse.java
  src/main/java/saphy/saphy/purchase/presentation/PurchaseController.java
  src/main/java/saphy/saphy/purchase/service/PurchaseService.java
Labels: ✨ Feature

#93 SAPHY-175 fix: 주문 가능 상태를 반환하는 메서드 오류 수정
  src/main/java/saphy/saphy/item/domain/Item.java
Labels: 🐞 Bug

#92 SAPHY-174 feat: 기기 판매 등록 및 판매 목록 조회 기능 구현
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/image/domain/SalesImage.java
  src/main/java/saphy/saphy/image/dto/StoreImageDto.java
  src/main/java/saphy/saphy/image/repository/SalesImageRepository.java
  src/main/java/saphy/saphy/image/service/ImageService.java
  src/main/java/saphy/saphy/item/dto/response/LaptopResponse.java
  src/main/java/saphy/saphy/item/dto/response/PhoneResponse.java
  src/main/java/saphy/saphy/item/dto/response/TabletResponse.java
  src/main/java/saphy/saphy/member/dto/response/MemberDetailResponse.java
  src/main/java/saphy/saphy/sales/domain/Defect.java
  src/main/java/saphy/saphy/sales/domain/Sales.java
  src/main/java/saphy/saphy/sales/domain/repository/SalesRepository.java
  src/main/java/saphy/saphy/sales/dto/request/SalesCreateRequest.java
  src/main/java/saphy/saphy/sales/dto/response/SalesResponse.java
  src/main/java/saphy/saphy/sales/presentation/SalesController.java
  src/main/java/saphy/saphy/sales/service/SalesService.java
Labels: ✨ Feature, ♻️ Refactor

#94 SAPHY-176 refactor: Redis 오류 수정
  src/main/java/saphy/saphy/global/config/RedisConfig.java
Labels: 🐞 Bug

#95 SAPHY-176 fix: redis error
  docker-compose.yml
Labels: 🐞 Bug

#96 SAPHY-57 feat : 상품 배송 현황 조회 기능 구현
  src/main/java/saphy/saphy/purchase/domain/repository/PurchaseRepository.java
  src/main/java/saphy/saphy/purchase/presentation/PurchaseController.java
  src/main/java/saphy/saphy/purchase/service/PurchaseService.java
Labels: ✨ Feature

#100 refactor: 결제 기능에 유저 엑세스 토큰 받아오도록 수정
  build.gradle
  src/main/java/saphy/saphy/pay/domain/Pay.java
  src/main/java/saphy/saphy/pay/dto/request/PayPrepareRequest.java
  src/main/java/saphy/saphy/pay/presentation/PayController.java
  src/main/java/saphy/saphy/pay/service/PayService.java
  src/main/java/saphy/saphy/purchase/domain/PaymentType.java
  src/main/java/saphy/saphy/purchase/domain/Purchase.java
  src/main/java/saphy/saphy/purchase/dto/response/PurchaseResponse.java
  src/main/java/saphy/saphy/purchase/service/PurchaseService.java
Labels: 🐞 Bug

#102 SAPHY-182 fix: 판매 엔티티 관련 에러 수정
  src/main/java/saphy/saphy/sales/domain/Defect.java
  src/main/java/saphy/saphy/sales/presentation/SalesController.java
Labels: 🐞 Bug, 🚑 Emergency
