Repository 2024-Saphy/BE, pull requests merged in 2024-08, with the labels that each got.

#28 카카오 회원가입 로그인 구현
  README.md
  build.gradle
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/domain/CustomUserDetails.java
  src/main/java/saphy/saphy/auth/domain/RefreshEntity.java
  src/main/java/saphy/saphy/auth/domain/dto/request/KakaoMemberCheckDto.java
  src/main/java/saphy/saphy/auth/domain/dto/request/KakaoSignUpDto.java
  src/main/java/saphy/saphy/auth/filter/CustomLogoutFilter.java
  src/main/java/saphy/saphy/auth/filter/JWTFilter.java
  src/main/java/saphy/saphy/auth/filter/LoginFilter.java
  src/main/java/saphy/saphy/auth/presentation/AuthController.java
  src/main/java/saphy/saphy/auth/presentation/KakaoController.java
  src/main/java/saphy/saphy/auth/presentation/ReissueController.java
  src/main/java/saphy/saphy/auth/repository/RefreshRepository.java
  src/main/java/saphy/saphy/auth/service/AuthService.java
  src/main/java/saphy/saphy/auth/service/CustomUserDetailsService.java
  src/main/java/saphy/saphy/auth/service/KaKaoService.java
  src/main/java/saphy/saphy/auth/service/ReissueService.java
  src/main/java/saphy/saphy/auth/service/TokenService.java
  src/main/java/saphy/saphy/auth/utils/AccessTokenUtils.java
  src/main/java/saphy/saphy/auth/utils/JWTUtil.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
  src/main/java/saphy/saphy/global/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/member/domain/Member.java
  src/main/java/saphy/saphy/member/domain/dto/request/JoinMemberDto.java
  src/main/java/saphy/saphy/member/domain/repository/MemberRepository.java
  src/main/java/saphy/saphy/member/domain/repository/UserRepository.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: ⚙ Chore, ✨ Feature, 🔒 Security

#31 SAPHY-41 refactor: 접근 권한 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/domain/RefreshEntity.java
  src/main/java/saphy/saphy/auth/service/TokenService.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
Labels: 🐞 Bug, 🔒 Security

#33 fix: application.yml에 JWT 설정을 추가한다
  src/main/resources/application.yml
Labels: 🐞 Bug, ⚙ Chore

#34 SAPHY-43 refactor: 카카오 로그인 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/presentation/KakaoController.java
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
Labels: 🐞 Bug

#35 Feat/saphy 43 social login
  src/main/java/saphy/saphy/auth/domain/dto/request/SocialLoginDTO.java
  src/main/java/saphy/saphy/auth/filter/LoginFilter.java
  src/main/java/saphy/saphy/auth/presentation/KakaoController.java
  src/main/java/saphy/saphy/auth/service/KaKaoService.java
  src/main/java/saphy/saphy/auth/service/SecurityService.java
  src/main/java/saphy/saphy/auth/service/SecurityServiceImpl.java
  src/main/java/saphy/saphy/member/domain/repository/MemberRepository.java
Labels: 🐞 Bug, ✨ Feature, 🔒 Security

#36 SAPHY-41 refactor: 인증 권한 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/presentation/KakaoController.java
Labels: 🐞 Bug

#37 Feat/saphy 43 social login
  src/main/java/saphy/saphy/auth/domain/RefreshEntity.java
  src/main/java/saphy/saphy/auth/domain/dto/request/OAuthLoginDTO.java
  src/main/java/saphy/saphy/auth/domain/dto/request/OAuthSignUpDto.java
  src/main/java/saphy/saphy/auth/filter/CustomLogoutFilter.java
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
  src/main/java/saphy/saphy/auth/presentation/ReissueController.java
  src/main/java/saphy/saphy/auth/service/KaKaoService.java
  src/main/java/saphy/saphy/auth/service/OAuthService.java
  src/main/java/saphy/saphy/auth/service/SecurityService.java
  src/main/java/saphy/saphy/auth/service/SecurityServiceImpl.java
Labels: ♻️ Refactor

#38 SAPHY-42 refactor: 소셜로그인 접근권한 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
Labels: 🐞 Bug, ♻️ Refactor

#39 SAPHY-42 refactor: 회원가입 로직 수정
  src/main/java/saphy/saphy/auth/domain/dto/request/OAuthSignUpDto.java
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
  src/main/java/saphy/saphy/auth/service/OAuthService.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: 🐞 Bug

#40 SAPHY-41 feat: 소셜로그인 SecurityContext 주입 로직 추가
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
  src/main/java/saphy/saphy/auth/service/OAuthService.java
  src/main/java/saphy/saphy/auth/service/SecurityService.java
  src/main/java/saphy/saphy/auth/service/SecurityServiceImpl.java
Labels: 🐞 Bug

#45 SAPHY-41 refactor: CORS 노출 헤더 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
  src/main/java/saphy/saphy/member/domain/dto/request/JoinMemberDto.java
Labels: 🔒 Security, ♻️ Refactor

#47 SAPHY-43 refactor: social login
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
Labels: ♻️ Refactor

#48 SAPHY-43 refactor: 초기 접근 권한 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
Labels: ♻️ Refactor

#49 SAPHY-43 refactor: jwt토큰 검증 필터 삽입 위치 변경
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
Labels: 🐞 Bug

#50 SAPHY-43 refactor: config 파일 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
Labels: ✅ Test

#51 SAPHY-54 feat : 회원 정보 변경 기능 구현
  src/main/java/saphy/saphy/member/domain/dto/request/MemberInfoUpdateDto.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: ✨ Feature

#52 SAPHY-62 기기 목록 조회 기능 구현
  src/main/java/saphy/saphy/global/entity/BaseEntity.java
  src/main/java/saphy/saphy/item/domain/Device.java
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/item/domain/Phone.java
  src/main/java/saphy/saphy/item/domain/enumeration/Brand.java
  src/main/java/saphy/saphy/item/domain/enumeration/Color.java
  src/main/java/saphy/saphy/item/domain/enumeration/DeviceType.java
  src/main/java/saphy/saphy/item/domain/enumeration/Grade.java
  src/main/java/saphy/saphy/item/domain/enumeration/Storage.java
  src/main/java/saphy/saphy/item/dto/request/ItemCreateRequest.java
  src/main/java/saphy/saphy/item/dto/response/ItemResponse.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/repository/ItemRepository.java
  src/main/java/saphy/saphy/item/service/ItemService.java
  src/main/java/saphy/saphy/order/domain/Order.java
Labels: ✨ Feature
