Repository 2024-Saphy/BE, pull requests merged in 2024-07, with the labels that each got.

#8 remove: 원격 저장소의 불필요한 파일 제거
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
Labels: 🔥 Remove

#17 feat: 전역 예외 핸들러 구현
  src/main/java/saphy/saphy/global/handler/GlobalExceptionHandler.java
Labels: ✨ Feature

#21 docs: README.md에 인프라 아키텍쳐 추가
  README.md
Labels: 📝 Docs

#25 CI를 테스트합니다.
  README.md
Labels: ✅ Test

#27 Test: Webhook, CI 테스트를 한다.
  .gitignore
  docker-compose.yml
  src/main/java/saphy/saphy/SaphyApplication.java
  src/main/java/saphy/saphy/global/HealthCheck.java
  src/main/resources/application.yml
  src/test/java/saphy/saphy/SaphyApplicationTests.java
Labels: 🌏 Infrastructure, ✅ Test, 🔒 Security, ♻️ Refactor

#30 Update README.md
  README.md
Labels: 📝 Docs
