Repository 2024-Saphy/BE, pull requests merged in 2024-09, with the labels that each got.

#53 SAPHY-138 feat: Swagger 환경 세팅
  build.gradle
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/filter/JWTFilter.java
  src/main/java/saphy/saphy/auth/filter/LoginFilter.java
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
  src/main/java/saphy/saphy/auth/presentation/ReissueController.java
  src/main/java/saphy/saphy/auth/service/CustomUserDetailsService.java
  src/main/java/saphy/saphy/auth/utils/JWTUtil.java
  src/main/java/saphy/saphy/global/HealthCheck.java
  src/main/java/saphy/saphy/global/config/SwaggerConfig.java
  src/main/java/saphy/saphy/member/domain/dto/request/JoinMemberDto.java
  src/main/java/saphy/saphy/member/domain/dto/response/MemberDetailDto.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: ⚙ Chore, ✨ Feature, 🔒 Security, ♻️ Refactor

#55 SAPHY-138 feat: Swagger 세팅 yml 추가
  src/main/resources/application.yml
Labels: ⚙ Chore, ✨ Feature

#54 refactor: 엔티티 수정
  src/main/java/saphy/saphy/bookmark/domain/Bookmark.java
  src/main/java/saphy/saphy/cart/domain/Cart.java
  src/main/java/saphy/saphy/cart/domain/repository/CartRepository.java
  src/main/java/saphy/saphy/cart/presentation/CartController.java
  src/main/java/saphy/saphy/contact/domain/Category.java
  src/main/java/saphy/saphy/contact/domain/Contact.java
  src/main/java/saphy/saphy/contact/domain/repository/ProductInquiryRepository.java
  src/main/java/saphy/saphy/contact/presentation/ContactController.java
  src/main/java/saphy/saphy/contact/service/ContactService.java
  src/main/java/saphy/saphy/coupon/domain/Coupon.java
  src/main/java/saphy/saphy/delivery/domain/Delivery.java
  src/main/java/saphy/saphy/delivery/domain/DeliveryStatus.java
  src/main/java/saphy/saphy/delivery/domain/repository/DeliveryRepository.java
  src/main/java/saphy/saphy/delivery/presentation/DeliveryController.java
  src/main/java/saphy/saphy/delivery/service/DeliveryService.java
  src/main/java/saphy/saphy/image/ItemImg.java
  src/main/java/saphy/saphy/image/ReviewImg.java
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/member/domain/Member.java
  src/main/java/saphy/saphy/order/domain/Order.java
  src/main/java/saphy/saphy/order/domain/OrderStatus.java
  src/main/java/saphy/saphy/productInquiry/domain/repository/ProductInquiryRepository.java
  src/main/java/saphy/saphy/productInquiry/service/ProductInquiryService.java
  src/main/java/saphy/saphy/purchaseHistory/domain/PurchaseHistory.java
  src/main/java/saphy/saphy/repairCenter/domain/RepairCenterBookmark.java
  src/main/java/saphy/saphy/repairCenter/domain/RepairCenterReview.java
  src/main/java/saphy/saphy/review/domain/Review.java
Labels: ♻️ Refactor

#56 SAPHY-138: Swagger CORS 접근 수정
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
  src/main/java/saphy/saphy/order/domain/repository/OrderRepository.java
  src/main/java/saphy/saphy/order/service/OrderService.java
Labels: 🐞 Bug, ⚙ Chore

#57 SAPHY-138 fix: CORS 접근 범위 변경
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
Labels: 🐞 Bug, ⚙ Chore

#59 엔티티 수정
  build.gradle
  src/main/java/saphy/saphy/member/service/MemberService.java
  src/main/java/saphy/saphy/order/domain/repository/OrderRepository.java
  src/main/java/saphy/saphy/order/service/OrderService.java
  src/main/java/saphy/saphy/purchase/domain/PaymentType.java
  src/main/java/saphy/saphy/purchase/domain/Purchase.java
  src/main/java/saphy/saphy/purchase/domain/PurchaseStatus.java
  src/main/java/saphy/saphy/purchase/domain/repository/PurchaseRepository.java
  src/main/java/saphy/saphy/purchase/presentation/PurchaseController.java
  src/main/java/saphy/saphy/purchase/service/PurchaseService.java
  src/main/java/saphy/saphy/purchaseHistory/domain/PurchaseStatus.java
  src/main/java/saphy/saphy/purchaseHistory/domain/repository/PurchaseHistoryRepository.java
  src/main/java/saphy/saphy/purchaseHistory/presentation/PurchaseHistoryController.java
  src/main/java/saphy/saphy/purchaseHistory/service/PurchaseHistoryService.java
  src/main/java/saphy/saphy/sales/SalesStatus.java
  src/main/java/saphy/saphy/sales/domain/Sales.java
  src/main/java/saphy/saphy/sales/domain/repository/SalesRepository.java
  src/main/java/saphy/saphy/sales/presentation/SalesController.java
  src/main/java/saphy/saphy/sales/service/SalesService.java
  src/main/java/saphy/saphy/salesHistory/domain/SalesHistory.java
  src/main/resources/application.yml
Labels: ♻️ Refactor

#60 SAPHY-138 refactor: PATCH 추가
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
Labels: 🐞 Bug, ⚙ Chore, 🔒 Security, ♻️ Refactor

#61 SAPHY-138: Saphy Server Swagger 파일 추가
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/SwaggerConfig.java
Labels: 🐞 Bug

#62 SAPHY-138: Saphy Server Swagger 파일 추가
  src/main/java/saphy/saphy/global/config/SwaggerConfig.java
Labels: 🐞 Bug

#64 SAPHY-138 refactor: saphy 사이트 디폴트로 변경
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/global/config/SwaggerConfig.java
Labels: ♻️ Refactor

#66 SAPHY-138 refactor: dto 네이밍 변경
  src/main/java/saphy/saphy/auth/domain/dto/request/OAuthJoinRequest.java
  src/main/java/saphy/saphy/auth/domain/dto/request/OAuthLoginRequest.java
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
  src/main/java/saphy/saphy/auth/service/OAuthService.java
  src/main/java/saphy/saphy/auth/service/SecurityService.java
  src/main/java/saphy/saphy/auth/service/SecurityServiceImpl.java
  src/main/java/saphy/saphy/global/config/SwaggerConfig.java
  src/main/java/saphy/saphy/member/domain/dto/request/MemberJoinRequest.java
  src/main/java/saphy/saphy/member/domain/dto/response/MemberDetailResponse.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: 🐞 Bug, ⚙ Chore, 🔒 Security, ♻️ Refactor

#67 SAPHY-54 refactor : 회원 정보 수정기능 리팩토링
  src/main/java/saphy/saphy/member/domain/dto/request/MemberInfoUpdateRequest.java
  src/main/java/saphy/saphy/member/domain/dto/response/MemberInfoResponse.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: 🐞 Bug, ♻️ Refactor

#68 SAPHY-156: 새로 정한 Code Convention 스타일 적용
  src/main/java/saphy/saphy/auth/config/SecurityConfig.java
  src/main/java/saphy/saphy/auth/domain/CustomUserDetails.java
  src/main/java/saphy/saphy/auth/domain/RefreshEntity.java
  src/main/java/saphy/saphy/auth/domain/repository/RefreshRepository.java
  src/main/java/saphy/saphy/auth/dto/request/OAuthJoinRequest.java
  src/main/java/saphy/saphy/auth/dto/request/OAuthLoginRequest.java
  src/main/java/saphy/saphy/auth/filter/CustomLogoutFilter.java
  src/main/java/saphy/saphy/auth/filter/JWTFilter.java
  src/main/java/saphy/saphy/auth/filter/LoginFilter.java
  src/main/java/saphy/saphy/auth/presentation/OAuthController.java
  src/main/java/saphy/saphy/auth/presentation/ReissueController.java
  src/main/java/saphy/saphy/auth/service/CustomUserDetailsService.java
  src/main/java/saphy/saphy/auth/service/OAuthService.java
  src/main/java/saphy/saphy/auth/service/ReissueService.java
  src/main/java/saphy/saphy/auth/service/SecurityService.java
  src/main/java/saphy/saphy/auth/service/SecurityServiceImpl.java
  src/main/java/saphy/saphy/auth/service/TokenService.java
  src/main/java/saphy/saphy/auth/utils/AccessTokenUtils.java
  src/main/java/saphy/saphy/auth/utils/JWTUtil.java
  src/main/java/saphy/saphy/global/HealthCheck.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
  src/main/java/saphy/saphy/global/config/SwaggerConfig.java
  src/main/java/saphy/saphy/global/entity/BaseEntity.java
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/global/exception/SaphyException.java
  src/main/java/saphy/saphy/image/ItemImg.java
  src/main/java/saphy/saphy/image/ReviewImg.java
  src/main/java/saphy/saphy/member/domain/Member.java
  src/main/java/saphy/saphy/member/domain/dto/request/MemberJoinRequest.java
  src/main/java/saphy/saphy/member/domain/repository/MemberRepository.java
  src/main/java/saphy/saphy/member/dto/request/MemberInfoUpdateRequest.java
  src/main/java/saphy/saphy/member/dto/request/MemberJoinRequest.java
  src/main/java/saphy/saphy/member/dto/response/MemberDetailResponse.java
  src/main/java/saphy/saphy/member/dto/response/MemberInfoResponse.java
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: ♻️ Refactor

#70 SAPHY-147 refactor: access 및 refresh token 만료주기 주입 방식 변경
  src/main/java/saphy/saphy/auth/filter/LoginFilter.java
  src/main/java/saphy/saphy/auth/service/ReissueService.java
  src/main/java/saphy/saphy/global/config/CorsMvcConfig.java
  src/main/resources/application.yml
Labels: 🐞 Bug, ♻️ Refactor

#71 SAPHY-39: fix: 토큰 만료 주기 주입 방식 변경
  src/main/resources/application.yml
Labels: 🐞 Bug

#73 SAPHY-66 feat : 찜 목록 삭제 기능 구현
  src/main/java/saphy/saphy/itemWish/domain/repository/ItemWishRepository.java
  src/main/java/saphy/saphy/itemWish/presentation/ItemWishController.java
  src/main/java/saphy/saphy/itemWish/service/ItemWishService.java
Labels: ✨ Feature

#74 Update application.yml
  src/main/resources/application.yml
Labels: ♻️ Refactor

#76 SAPHY-72 feat : 상품 삭제 기능 구현
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
Labels: ✨ Feature

#77 SAPHY-161 feat: 이미지 엔티티 및 관련 로직 구현
  build.gradle
  src/main/java/saphy/saphy/global/config/S3Config.java
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/global/exception/SaphyException.java
  src/main/java/saphy/saphy/image/ItemImg.java
  src/main/java/saphy/saphy/image/ReviewImg.java
  src/main/java/saphy/saphy/image/domain/Image.java
  src/main/java/saphy/saphy/image/domain/ItemImage.java
  src/main/java/saphy/saphy/image/domain/ProfileImage.java
  src/main/java/saphy/saphy/image/domain/ReviewImage.java
  src/main/java/saphy/saphy/image/dto/StoreImageDto.java
  src/main/java/saphy/saphy/image/dto/response/ImageResponse.java
  src/main/java/saphy/saphy/image/repository/ImageStoreProcessor.java
  src/main/java/saphy/saphy/image/repository/ItemImageRepository.java
  src/main/java/saphy/saphy/image/repository/ProfileImageRepository.java
  src/main/java/saphy/saphy/image/repository/ReviewImageRepository.java
  src/main/java/saphy/saphy/image/service/ImageService.java
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/item/dto/response/PhoneResponse.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
  src/main/java/saphy/saphy/member/domain/Member.java
  src/main/java/saphy/saphy/review/domain/Review.java
  src/main/resources/application.yml
Labels: ⚙ Chore, ✨ Feature

#78 SAPHY-52 feat: 서비스 탈퇴 기능 구현
  src/main/java/saphy/saphy/member/presentation/MemberController.java
  src/main/java/saphy/saphy/member/service/MemberService.java
Labels: ✨ Feature

#79 SAPHY-167 feat: 기기 조회 기능 개편
  build.gradle
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/image/service/ImageService.java
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/item/domain/repository/ItemRepository.java
  src/main/java/saphy/saphy/item/dto/request/LaptopCreateRequest.java
  src/main/java/saphy/saphy/item/dto/request/PhoneCreateRequest.java
  src/main/java/saphy/saphy/item/dto/request/TabletCreateRequest.java
  src/main/java/saphy/saphy/item/dto/response/ItemResponse.java
  src/main/java/saphy/saphy/item/dto/response/LaptopResponse.java
  src/main/java/saphy/saphy/item/dto/response/PhoneResponse.java
  src/main/java/saphy/saphy/item/dto/response/TabletResponse.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
  src/main/java/saphy/saphy/itemWish/service/ItemWishService.java
Labels: ✨ Feature

#80 SAPHY-167 feat: 기기 조회 기능 개편
  src/main/java/saphy/saphy/item/domain/enumeration/DeviceType.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
  src/main/resources/application.yml
Labels: ✨ Feature, ♻️ Refactor

#81 SAPHY-140 feat: 결제 기능
  build.gradle
  src/main/java/saphy/saphy/global/config/IamportConfig.java
  src/main/java/saphy/saphy/global/exception/ErrorCode.java
  src/main/java/saphy/saphy/global/handler/GlobalExceptionHandler.java
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/pay/domain/Pay.java
  src/main/java/saphy/saphy/pay/domain/PayMethod.java
  src/main/java/saphy/saphy/pay/domain/PayStatus.java
  src/main/java/saphy/saphy/pay/domain/repository/PayRepository.java
  src/main/java/saphy/saphy/pay/dto/request/PayRequest.java
  src/main/java/saphy/saphy/pay/dto/response/PayResponse.java
  src/main/java/saphy/saphy/pay/presentation/PayController.java
  src/main/java/saphy/saphy/pay/service/PayService.java
Labels: ✨ Feature, ♻️ Refactor

#82 SAPHY-65 feat : 찜 목록 조회 기능 구현
  src/main/java/saphy/saphy/itemWish/domain/repository/ItemWishRepository.java
  src/main/java/saphy/saphy/itemWish/presentation/ItemWishController.java
  src/main/java/saphy/saphy/itemWish/service/ItemWishService.java
Labels: ✨ Feature

#83 SAPHY-71 feat : 기기 정보 수정 기능 구현
  src/main/java/saphy/saphy/item/domain/Item.java
  src/main/java/saphy/saphy/item/domain/Laptop.java
  src/main/java/saphy/saphy/item/domain/Phone.java
  src/main/java/saphy/saphy/item/domain/Tablet.java
  src/main/java/saphy/saphy/item/dto/request/LaptopUpdateRequest.java
  src/main/java/saphy/saphy/item/dto/request/PhoneUpdateRequest.java
  src/main/java/saphy/saphy/item/dto/request/TabletUpdateRequest.java
  src/main/java/saphy/saphy/item/presentation/ItemController.java
  src/main/java/saphy/saphy/item/service/ItemService.java
Labels: 💻 Admin, ✨ Feature, ♻️ Refactor

#84 SAPHY-168 feat: redis 환경 세팅
  build.gradle
  src/main/java/saphy/saphy/auth/domain/RefreshEntity.java
  src/main/java/saphy/saphy/auth/filter/LoginFilter.java
  src/main/java/saphy/saphy/auth/presentation/ReissueController.java
  src/main/java/saphy/saphy/auth/service/ReissueService.java
  src/main/java/saphy/saphy/auth/utils/JWTUtil.java
  src/main/java/saphy/saphy/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: ⚙ Chore, ✨ Feature
